config/routes.rb
Rails.application.routes.draw do
  resources :protocols

  get 'main_menu/index'

  devise_for :users

  root 'main_menu#index'

end

app/models/protocol.rb
class Protocol < ActiveRecord::Base
  validates :ware, length: { minimum: 3 }
  validates :price, numericality: { greater_than: 0 }
  validates :amount_owed, numericality: { greater_than_or_equal_to: 0 }

  monetize :price_Øres
  monetize :amount_owed_Øres

  belongs_to :buyer, class_name: 'User'
  belongs_to :debtor, class_name: 'User'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/main_menu_controller.rb
class MainMenuController < ApplicationController

  def index
  end
end

app/controllers/protocols_controller.rb
class ProtocolsController < ApplicationController
  before_action :set_protocol, only: [:edit, :update, :destroy]

  # GET /protocols
  # GET /protocols.json
  def index
    current_user_id = current_user.id
    @protocols = Protocol.all.where('buyer_id = ? OR debtor_id = ?', current_user_id, current_user_id)

    @overview = {}
    User.all.each { |user| @overview[user.id] = [user.name, Money.new(0)] }

    @protocols.each do |protocol|
      if protocol.debtor_id == current_user.id
        @overview[protocol.buyer_id][1] += protocol.amount_owed
      else
        @overview[protocol.debtor_id][1] -= protocol.amount_owed
      end
    end
  end

  # GET /protocols/new
  def new
    @users = User.all
    @protocol = Protocol.new
  end

  # GET /protocols/1/edit
  def edit
  end

  # POST /protocols
  # POST /protocols.json
  def create
    @protocol = Protocol.new
    @users = User.all

    @protocol = Protocol.new protocol_params
    @protocol.valid?
    if not params.has_key? :debtors or (params[:debtors].one? and params[:debtors].values.first == current_user.id.to_s)
      @protocol.errors[:debtors] = 'You must set at least one debtor other than yourself.'
    end

    if @protocol.errors.empty?
      debtors = params.require(:debtors)
      create_protocol_for_each_debtor debtors, protocol_params
    end

    respond_to do |format|
      if @protocol.errors.empty?
        format.html { redirect_to new_protocol_path, notice: 'Protocols were successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

# PATCH/PUT /protocols/1
# PATCH/PUT /protocols/1.json
  def update
    respond_to do |format|
      if @protocol.update(protocol_params)
        format.html { redirect_to @protocol, notice: 'Protocol was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

# DELETE /protocols/1
# DELETE /protocols/1.json
  def destroy
    @protocol.destroy
    respond_to do |format|
      format.html { redirect_to protocols_url, notice: 'Protocol was successfully destroyed.' }
    end
  end

  private
# Use callbacks to share common setup or constraints between actions.
  def set_protocol
    @protocol = Protocol.find(params[:id])
  end

# Never trust parameters from the scary internet, only allow the white list through.
  def protocol_params
    params.require(:protocol).permit(:ware, :price, :amount_owed)
  end

  def create_protocol_for_each_debtor(debtors, protocol_params)
    if valid_debtors? debtors
      debtors.each_key do |debtor_key|
        unless debtors[debtor_key].to_s == current_user.id.to_s
          protocol = Protocol.new protocol_params
          protocol.buyer = current_user
          protocol.debtor_id = debtors[debtor_key]
          protocol.amount_owed = protocol_params[:price].to_f / debtors.length
          protocol.save
        end
      end
    end
  end

  def valid_debtors? (debtors)
    debtors.each_value do |id|
      unless User.exists? id
        return false
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_menu_helper.rb
module MainMenuHelper
end

app/helpers/protocols_helper.rb
module ProtocolsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SpRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'defaults', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main_menu/index.html.erb
<p>Find me in app/views/main_menu/index.html.erb</p>

app/views/protocols/_form.html.erb
<%= form_for(@protocol) do |f| %>
    <% if @protocol.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@protocol.errors.count, "error") %> prohibited this protocol from being saved:</h2>

            <ul>
                <% @protocol.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= f.label :ware %><br>
        <%= f.text_field :ware %>
    </div>
    <div class="field">
        <%= f.label :price %><br>
        <%= f.text_field :price %>
    </div>
    <div class="<%= @protocol.errors[:debtors].any? ? 'field_with_errors' : 'field' %>">
        <% @users.each do |user| %>
            <%= check_box_tag "debtors[#{user.email}]", user.id %>
            <%= label_tag "debtors[#{user.email}]", user.name %><br>
        <% end %>
    </div>
    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

app/views/protocols/edit.html.erb
<h1>Editing protocol</h1>

<%= render 'form' %>

<%= link_to 'Show', @protocol %> |
<%= link_to 'Back', protocols_path %>

app/views/protocols/index.html.erb
<h1>Listing protocols</h1>

<% @overview.each_value do |row| %>
    <% (name, amount_owed) = row %>
    <div><%= name %> &nbsp;&nbsp;&nbsp;&nbsp; <%= amount_owed %></div>
<% end %>

<table>
    <thead>
    <tr>
        <th>Ware</th>
        <th>Price</th>
        <th>Amount owed</th>
        <th>Buyer</th>
        <th>Debtor</th>
        <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @protocols.each do |protocol| %>
        <tr>
            <td><%= protocol.ware %></td>
            <td><%= protocol.price %></td>
            <td><%= protocol.amount_owed %></td>
            <td><%= protocol.buyer.name %></td>
            <td><%= protocol.debtor.name %></td>
            <td><%= link_to 'Edit', edit_protocol_path(protocol) %></td>
            <td><%= link_to 'Destroy', protocol, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
    <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New Protocol', new_protocol_path %>

app/views/protocols/new.html.erb
<h1>New protocol</h1>

<p id="notice"><%= notice %></p>

<%= render 'form' %>

<%= link_to 'Back', protocols_path %>